@MailSender_HostAddress = https://localhost:7290

POST {{MailSender_HostAddress}}/api/email/send
Content-Type: application/json

{
    "to": "fouquet.francois@gmail.com",
    "subject": "Test depuis MailSender API",
    "message": "Ceci est un message de test envoyé depuis l'API MailSender utilisant SMTP."
}

###
